/**
 * Complete type definitions for the SunoAPI SDK.
 *
 * All request/response shapes are derived from the published OpenAPI specs
 * (suno-api.json, suno-voice-api.json, file-upload-api.json) published at
 * https://docs.sunoapi.org.
 *
 * Two different response envelopes exist:
 *  - The **main** and **voice** APIs wrap results in `{ code, msg, data }`.
 *  - The **file upload** API wraps results in `{ success, code, msg, data }`.
 *
 * This SDK transparently unwraps the `data` field for you, so every method
 * returns the inner payload directly.
 */

/* ============================================================================
 * Enums
 * ========================================================================== */

/**
 * Available music generation models.
 *
 * - `V5_5` — "Unleash Your Voice": custom models tailored to your unique taste.
 * - `V5`   — latest general model.
 * - `V4_5ALL`, `V4_5PLUS`, `V4_5`, `V4` — progressively older generations.
 *
 * Some features (e.g. `duration`) are only supported on specific models.
 */
export type SongGenerationModel =
  | 'V4'
  | 'V4_5'
  | 'V4_5PLUS'
  | 'V4_5ALL'
  | 'V5'
  | 'V5_5';

/** Runtime values for {@link SongGenerationModel}. Use `SongGenerationModel.V4_5PLUS` for convenience. */
export const SongGenerationModel = {
  V4: 'V4', V4_5: 'V4_5', V4_5PLUS: 'V4_5PLUS', V4_5ALL: 'V4_5ALL', V5: 'V5', V5_5: 'V5_5',
} as const;

/**
 * Sounds generation only supports the `V5` model.
 */
export type SoundGenerationModel = 'V5';

/** Runtime value for {@link SoundGenerationModel}. */
export const SoundGenerationModel = { V5: 'V5' } as const;

/**
 * Preferred vocal gender for generated vocals.
 */
export type VocalGender = 'm' | 'f';

/** Runtime values for {@link VocalGender}. */
export const VocalGender = { Male: 'm', Female: 'f' } as const;

/**
 * Persona model type used when applying a `personaId` to generated music.
 *
 * - `style_persona`  (default) — for Persona IDs generated by the
 *   "Generate Persona" endpoint.
 * - `voice_persona` — for voice-style personas.
 */
export type PersonaModel = 'style_persona' | 'voice_persona';

/** Runtime values for {@link PersonaModel}. */
export const PersonaModel = { Style: 'style_persona', Voice: 'voice_persona' } as const;

/**
 * Models accepted by the "Add Instrumental" and "Add Vocals" endpoints.
 * Defaults to `V4_5PLUS`.
 */
export type AddTrackModel = 'V4_5PLUS' | 'V5' | 'V5_5';

/** Runtime values for {@link AddTrackModel}. */
export const AddTrackModel = { V4_5PLUS: 'V4_5PLUS', V5: 'V5', V5_5: 'V5_5' } as const;

/**
 * Musical key for sound generation.
 */
export type SoundKey =
  | 'Any'
  | 'Cm' | 'C#m' | 'Dm' | 'D#m' | 'Em' | 'Fm' | 'F#m' | 'Gm' | 'G#m' | 'Am' | 'A#m' | 'Bm'
  | 'C' | 'C#' | 'D' | 'D#' | 'E' | 'F' | 'F#' | 'G' | 'G#' | 'A' | 'A#' | 'B';

/** Runtime values for {@link SoundKey}. */
export const SoundKey = {
  Any: 'Any',
  Cm: 'Cm', CmSharp: 'C#m', Dm: 'Dm', DmSharp: 'D#m', Em: 'Em', Fm: 'Fm', FmSharp: 'F#m',
  Gm: 'Gm', GmSharp: 'G#m', Am: 'Am', AmSharp: 'A#m', Bm: 'Bm',
  C: 'C', CSharp: 'C#', D: 'D', DSharp: 'D#', E: 'E', F: 'F', FSharp: 'F#',
  G: 'G', GSharp: 'G#', A: 'A', ASharp: 'A#', B: 'B',
} as const;

/**
 * Vocal / instrument separation type.
 *
 * - `separate_vocal`       — split into vocals + accompaniment.
 * - `split_stem`           — split into common stems (drums, bass, ...).
 * - `split_stem_advanced`  — split into one specific instrument (`stemName`).
 */
export type VocalSeparationType = 'separate_vocal' | 'split_stem' | 'split_stem_advanced';

/** Runtime values for {@link VocalSeparationType}. */
export const VocalSeparationType = {
  SeparateVocal: 'separate_vocal', SplitStem: 'split_stem', SplitStemAdvanced: 'split_stem_advanced',
} as const;

/**
 * When `type` is `split_stem_advanced`, this selects the exact instrument to
 * isolate. (Only a subset of the most common values is shown below; the API
 * accepts the full list published in its spec.)
 */
export type StemName =
  | 'Lead Vocal' | 'Drum Kit' | 'Kick' | 'Snare' | 'Bass' | 'Backing Vocals'
  | 'Piano' | 'Electric Guitar' | 'Percussion' | 'String Section' | 'Synth'
  | 'Acoustic Guitar' | 'Brass Section' | 'Organ' | 'Electric Bass' | 'Cello'
  | 'Violin' | 'Trumpet' | 'Saxophone' | 'Choir' | 'Banjo' | 'Flute'
  | 'Guitar' | 'Keyboard' | 'Drums' | 'Strings' | 'FX' | 'Woodwinds';

/** Runtime values for {@link StemName}. */
export const StemName = {
  LeadVocal: 'Lead Vocal', DrumKit: 'Drum Kit', Kick: 'Kick', Snare: 'Snare', Bass: 'Bass',
  BackingVocals: 'Backing Vocals', Piano: 'Piano', ElectricGuitar: 'Electric Guitar',
  Percussion: 'Percussion', StringSection: 'String Section', Synth: 'Synth',
  AcousticGuitar: 'Acoustic Guitar', BrassSection: 'Brass Section', Organ: 'Organ',
  ElectricBass: 'Electric Bass', Cello: 'Cello', Violin: 'Violin', Trumpet: 'Trumpet',
  Saxophone: 'Saxophone', Choir: 'Choir', Banjo: 'Banjo', Flute: 'Flute', Guitar: 'Guitar',
  Keyboard: 'Keyboard', Drums: 'Drums', Strings: 'Strings', FX: 'FX', Woodwinds: 'Woodwinds',
} as const;

/**
 * Generic task status returned by music / lyrics record-info endpoints.
 */
export type TaskStatus = 'PENDING' | 'GENERATING' | 'SUCCESS' | 'FAILED';

/** Runtime values for {@link TaskStatus}. */
export const TaskStatus = {
  PENDING: 'PENDING', GENERATING: 'GENERATING', SUCCESS: 'SUCCESS', FAILED: 'FAILED',
} as const;

/**
 * Voice validation / generation status.
 */
export type VoiceStatus =
  | 'wait_processing'
  | 'processing_validate'
  | 'processing_validate_fail'
  | 'wait_validating'
  | 'success'
  | 'fail';

/** Runtime values for {@link VoiceStatus}. */
export const VoiceStatus = {
  WaitProcessing: 'wait_processing', ProcessingValidate: 'processing_validate',
  ProcessingValidateFail: 'processing_validate_fail', WaitValidating: 'wait_validating',
  Success: 'success', Fail: 'fail',
} as const;

/**
 * Supported voice languages for the "Validate Voice" endpoint.
 */
export type VoiceLanguage = 'en' | 'zh' | 'es' | 'fr' | 'pt' | 'de' | 'ja' | 'ko' | 'hi' | 'ru';

/** Runtime values for {@link VoiceLanguage}. */
export const VoiceLanguage = {
  English: 'en', Chinese: 'zh', Spanish: 'es', French: 'fr', Portuguese: 'pt', German: 'de',
  Japanese: 'ja', Korean: 'ko', Hindi: 'hi', Russian: 'ru',
} as const;

/**
 * Singer skill level for the "Generate Voice" endpoint. Defaults to `beginner`.
 */
export type SingerSkillLevel = 'beginner' | 'intermediate' | 'advanced' | 'professional';

/** Runtime values for {@link SingerSkillLevel}. */
export const SingerSkillLevel = {
  Beginner: 'beginner', Intermediate: 'intermediate', Advanced: 'advanced', Professional: 'professional',
} as const;

/* ============================================================================
 * Response envelopes
 * ========================================================================== */

/**
 * Envelope returned by the main & voice APIs.
 * The SDK unwraps `data` for you — you normally never see this object.
 */
export interface ApiResponse<T> {
  /** `200` indicates success; any other value is an error. */
  code: number;
  /** Human readable message. */
  msg: string;
  /** The actual payload. */
  data: T;
}

/**
 * Envelope returned by the file-upload API (note the `success` boolean).
 */
export interface UploadApiResponse<T> {
  success: boolean;
  code: number;
  msg: string;
  data: T;
}

/* ============================================================================
 * Shared / reused payloads
 * ========================================================================== */

/**
 * A single generated track as returned inside a music record-info response.
 *
 * > Note: record-info responses use **camelCase** (`audioUrl`), while the
 * > asynchronous callback payloads use **snake_case** (`audio_url`). This SDK
 * > models the record-info shape.
 */
export interface AudioTrack {
  /** Unique track id (use with extend / wav / midi / video / persona). */
  id: string;
  /** Direct download URL of the generated audio. */
  audioUrl: string;
  /** Streamable audio URL. */
  streamAudioUrl: string;
  /** Cover art URL. */
  imageUrl: string;
  /** The prompt that produced this track. */
  prompt: string;
  /** Model name that generated the track. */
  modelName: string;
  /** Track title. */
  title: string;
  /** Comma separated style tags. */
  tags: string;
  /** Creation timestamp (ISO string). */
  createTime: string;
  /** Duration in seconds. */
  duration: number;
}

/**
 * A single lyrics item returned inside a lyrics record-info response.
 */
export interface LyricsItem {
  /** The generated lyrics text. */
  text: string;
  /** Title of the lyrics. */
  title: string;
  /** Status of the lyrics item. */
  status: string;
  /** Error message if generation failed. */
  errorMessage: string;
}

/**
 * One word-aligned lyric token (used by the timestamped-lyrics endpoint).
 */
export interface AlignedWord {
  word: string;
  success: boolean;
  /** Start time in seconds. */
  startS: number;
  /** End time in seconds. */
  endS: number;
  palign: number;
}

/**
 * One separated instrument stem.
 */
export interface OriginData {
  /** Duration in seconds. */
  duration: number;
  /** Download URL of this stem. */
  audio_url: string;
  /** Group / instrument name of this stem. */
  stem_type_group_name: string;
  /** Stem id. */
  id: string;
}

/**
 * A single MIDI instrument and its notes.
 */
export interface MidiInstrument {
  /** Instrument name. */
  name: string;
  /** Note events for this instrument. */
  notes: MidiNote[];
}

/**
 * A single MIDI note event.
 */
export interface MidiNote {
  /** MIDI pitch (0-127). */
  pitch: number;
  /** Start time in seconds. */
  start: number;
  /** End time in seconds. */
  end: number;
  /** Velocity (0-127). */
  velocity: number;
}

/* ============================================================================
 * Request parameters — Music
 * ========================================================================== */

/** Common advanced controls shared by most music endpoints. */
export interface AdvancedMusicControls {
  /** Persona id to apply (optional). */
  personaId?: string;
  /** Persona model type when using `personaId`. @default 'style_persona' */
  personaModel?: PersonaModel;
  /** Styles to avoid (e.g. "Heavy Metal, Upbeat Drums"). */
  negativeTags?: string;
  /** Preferred vocal gender. */
  vocalGender?: VocalGender;
  /** Style adherence weight, 0.00–1.00. */
  styleWeight?: number;
  /** Creativity / novelty constraint, 0.00–1.00. */
  weirdnessConstraint?: number;
  /** Input-audio influence weight, 0.00–1.00. */
  audioWeight?: number;
}

/** Parameters accepted by every music generation request. */
export interface GenerateMusicParams extends AdvancedMusicControls {
  /**
   * Custom Mode enables advanced controls (`style` + `title` required;
   * `prompt` required when `instrumental` is `false`).
   */
  customMode: boolean;
  /** `true` = instrumental (no lyrics). */
  instrumental: boolean;
  /** Model version. */
  model: SongGenerationModel;
  /** Callback URL for completion notifications. */
  callBackUrl: string;
  /**
   * Description of the desired audio. Required in Custom Mode when
   * `instrumental` is `false`.
   */
  prompt?: string;
  /** Music style / genre. Required in Custom Mode. */
  style?: string;
  /** Track title. Required in Custom Mode. */
  title?: string;
  /**
   * Duration in seconds (10–360). Only effective when `model` is `V5_5`
   * and `customMode` is `true`. Must be an integer.
   */
  duration?: number;
}

/** Parameters for extending an existing track. */
export interface ExtendMusicParams extends AdvancedMusicControls {
  /**
   * `true` = use custom parameters (`continueAt`, `style`, `title` required;
   * `prompt` required when `instrumental` is `false`).
   */
  defaultParamFlag: boolean;
  /** Audio id of the track to extend. */
  audioId: string;
  /** Callback URL for completion notifications. */
  callBackUrl: string;
  /** Model version (must match the source track). */
  model: SongGenerationModel;
  /** `true` = instrumental. If `true`, `prompt` / `vocalGender` must be omitted. */
  instrumental?: boolean;
  /** Description of how to extend. Required when custom params & not instrumental. */
  prompt?: string;
  /** Music style, e.g. "Jazz". */
  style?: string;
  /** Music title. */
  title?: string;
  /** Start time (seconds) to begin the extension. Required in custom mode. */
  continueAt?: number;
}

/** Parameters for cover generation from an uploaded audio file. */
export interface UploadCoverParams extends GenerateMusicParams {
  /** URL of the uploaded audio (max 8 minutes). Required in all modes. */
  uploadUrl: string;
}

/** Parameters for extending from an uploaded audio file. */
export interface UploadExtendParams extends AdvancedMusicControls {
  /** URL of the uploaded audio (max 8 minutes). Required in all modes. */
  uploadUrl: string;
  /** Custom parameter mode toggle. */
  defaultParamFlag: boolean;
  /** Model version (must match the source audio). */
  model: SongGenerationModel;
  /** Callback URL. */
  callBackUrl: string;
  /** `true` = instrumental. */
  instrumental?: boolean;
  /** Extension description (optional in all cases). */
  prompt?: string;
  /** Music style. Required when `defaultParamFlag` is `true`. */
  style?: string;
  /** Music title. Required when `defaultParamFlag` is `true`. */
  title?: string;
  /** Start time (seconds) to begin the extension. Required in custom mode. */
  continueAt?: number;
  /** Duration (seconds), only when custom mode & `V5_5`. */
  duration?: number;
}

/** Parameters for a mashup of exactly two uploaded tracks. */
export interface MashupParams extends AdvancedMusicControls {
  /** Exactly 2 accessible audio URLs to mash up. */
  uploadUrlList: string[];
  /** Custom Mode toggle. */
  customMode: boolean;
  /** Model version. */
  model: SongGenerationModel;
  /** Callback URL. */
  callBackUrl: string;
  /** Description of the desired audio. */
  prompt?: string;
  /** Music style / genre. Required in Custom Mode. */
  style?: string;
  /** Track title. Required in Custom Mode. */
  title?: string;
  /** `true` = instrumental. */
  instrumental?: boolean;
  /** Duration (seconds), only when custom mode & `V5_5`. */
  duration?: number;
}

/** Parameters for generating a reusable Persona from a track. */
export interface GeneratePersonaParams {
  /** Source generation task id. */
  taskId: string;
  /** Audio id to create the Persona from. */
  audioId: string;
  /** Persona name. */
  name: string;
  /** Detailed description of the persona's musical character. */
  description: string;
  /** Analysis start (seconds). @default 0.0 */
  vocalStart?: number;
  /** Analysis end (seconds). @default 30.0 */
  vocalEnd?: number;
  /** Optional style label. */
  style?: string;
}

/** Parameters for replacing a section of an existing track. */
export interface ReplaceSectionParams {
  /** The replaced lyrics for the segment. */
  prompt: string;
  /** Music style tags. */
  tags: string;
  /** Music title. */
  title: string;
  /** Excluded styles (optional). */
  negativeTags?: string;
  /** Replacement start (seconds, 2 decimals). Must be < `infillEndS`. */
  infillStartS: number;
  /** Replacement end (seconds, 2 decimals). Must be > `infillStartS`. */
  infillEndS: number;
  /** Full lyrics (modified + unmodified) used for the whole track. */
  fullLyrics: string;
  /** Optional callback URL. */
  callBackUrl?: string;
}

/** Parameters for adding an instrumental to an uploaded track. */
export interface AddInstrumentalParams extends AdvancedMusicControls {
  /** URL of the uploaded track. */
  uploadUrl: string;
  /** Track title. */
  title: string;
  /** Styles to avoid. */
  negativeTags: string;
  /** Desired style / mood / instruments. */
  tags: string;
  /** Callback URL. */
  callBackUrl: string;
  /** Model version. @default 'V4_5PLUS' */
  model?: AddTrackModel;
}

/** Parameters for adding vocals to an uploaded track. */
export interface AddVocalsParams extends AdvancedMusicControls {
  /** Description of the vocals to generate. */
  prompt: string;
  /** Track title. */
  title: string;
  /** Styles / vocal traits to avoid. */
  negativeTags: string;
  /** Music & vocal style. */
  style: string;
  /** URL of the uploaded track. */
  uploadUrl: string;
  /** Callback URL. */
  callBackUrl: string;
  /** Model version. @default 'V4_5PLUS' */
  model?: AddTrackModel;
}

/* ============================================================================
 * Request parameters — Sounds / Lyrics / WAV / Separation / MIDI / Video / Cover / Style
 * ========================================================================== */

/** Parameters for sound effect generation. */
export interface GenerateSoundsParams {
  /** Prompt text (max 500 chars). */
  prompt: string;
  /** Model — sounds only support `V5`. */
  model: SoundGenerationModel;
  /** Enable loop playback. */
  soundLoop?: boolean;
  /** BPM (1–300). Omit for auto. */
  soundTempo?: number;
  /** Musical key. @default 'Any' */
  soundKey?: SoundKey;
  /** Fetch lyric subtitle data after completion. */
  grabLyrics?: boolean;
  /** Optional callback URL. */
  callBackUrl?: string;
}

/** Parameters for lyrics generation. */
export interface GenerateLyricsParams {
  /** Detailed lyrics description. */
  prompt: string;
  /** Callback URL (single `complete` stage). */
  callBackUrl: string;
}

/** Parameters for retrieving timestamped (word-aligned) lyrics. */
export interface TimestampedLyricsParams {
  /** Music generation task id. */
  taskId: string;
  /** Audio id of the track. */
  audioId: string;
}

/** Parameters for WAV conversion. */
export interface ConvertToWavParams {
  /** Music generation task id. */
  taskId: string;
  /** Specific audio id to convert. */
  audioId: string;
  /** Callback URL. */
  callBackUrl: string;
}

/** Parameters for vocal / stem separation. */
export interface SeparateVocalsParams {
  /** Callback URL (required for all separation requests). */
  callBackUrl: string;
  /** Existing audio id (from a prior generation callback). */
  audioId?: string;
  /** Separation type. */
  type?: VocalSeparationType;
  /** Instrument to isolate (only for `split_stem_advanced`). */
  stemName?: StemName;
}

/** Parameters for MIDI generation from a separated track. */
export interface GenerateMidiParams {
  /** Task id from a completed vocal separation. */
  taskId: string;
  /** Callback URL. */
  callBackUrl: string;
  /** Optional specific separated audio id. */
  audioId?: string;
}

/** Parameters for music-video (MP4) generation. */
export interface CreateMusicVideoParams {
  /** Music generation task id. */
  taskId: string;
  /** Specific audio id to convert. */
  audioId: string;
  /** Callback URL. */
  callBackUrl: string;
  /** Artist name shown in the video (max 50 chars). */
  author?: string;
  /** Brand / website watermark (max 50 chars). */
  domainName?: string;
}

/** Parameters for cover generation from an existing task. */
export interface GenerateCoverParams {
  /** Original music task id. */
  taskId: string;
  /** Callback URL. */
  callBackUrl: string;
}

/** Parameters for boosting / describing a music style. */
export interface BoostMusicStyleParams {
  /** Concise style description, e.g. "Pop, Mysterious". */
  content: string;
}

/* ============================================================================
 * Request parameters — Voice
 * ========================================================================== */

/** Parameters for validating a voice sample. */
export interface ValidateVoiceParams {
  /** URL of the voice sample. */
  voiceUrl: string;
  /** Analysis start (seconds). */
  vocalStartS: number;
  /** Analysis end (seconds). */
  vocalEndS: number;
  /** Sample language. */
  language?: VoiceLanguage;
  /** Optional callback URL. */
  callBackUrl?: string;
}

/** Parameters for generating a custom voice model. */
export interface GenerateVoiceParams {
  /** Validation task id. */
  taskId: string;
  /** Verified voice URL. */
  verifyUrl: string;
  /** Voice model name. */
  voiceName?: string;
  /** Voice description. */
  description?: string;
  /** Music style label. */
  style?: string;
  /** Skill level. @default 'beginner' */
  singerSkillLevel?: SingerSkillLevel;
  /** Optional callback URL. */
  callBackUrl?: string;
}

/** Parameters for regenerating a voice model. */
export interface RegenerateVoiceParams {
  /** Validation / generation task id. */
  taskId: string;
  /** Callback URL. NOTE: the API expects the field spelled `calBackUrl`. */
  calBackUrl: string;
}

/** Parameters for checking voice availability. */
export interface CheckVoiceParams {
  /** Task id to check. NOTE: the API expects the field spelled `task_id`. */
  task_id: string;
}

/* ============================================================================
 * Request parameters — File upload
 * ========================================================================== */

/** Upload a file via base64 content. */
export interface UploadFileBase64Params {
  /** Base64-encoded file content. */
  base64Data: string;
  /** Server-side upload path. */
  uploadPath: string;
  /** Optional file name. */
  fileName?: string;
}

/** Upload a file via a direct URL. */
export interface UploadFileUrlParams {
  /** Publicly reachable file URL. */
  fileUrl: string;
  /** Server-side upload path. */
  uploadPath: string;
  /** Optional file name. */
  fileName?: string;
}

/** Upload a file via a raw binary stream (multipart). */
export interface UploadFileStreamParams {
  /** File contents. */
  file: Buffer | Uint8Array | Blob | string;
  /** Server-side upload path. */
  uploadPath: string;
  /** Optional file name. */
  fileName?: string;
}

/* ============================================================================
 * Response payloads
 * ========================================================================== */

/** Returned by every "create task" endpoint — just the new task id. */
export interface TaskCreated {
  taskId: string;
}

/** Music generation record-info payload. */
export interface MusicGenerationRecord {
  taskId: string;
  parentMusicId: string;
  param: string;
  response: {
    taskId: string;
    sunoData: AudioTrack[];
  };
  /** @see TaskStatus */
  status: TaskStatus;
  type: string;
  operationType: string;
  errorCode: number;
  errorMessage: string;
}

/** Lyrics generation record-info payload. */
export interface LyricsGenerationRecord {
  taskId: string;
  param: string;
  response: {
    taskId: string;
    data: LyricsItem[];
  };
  status: TaskStatus;
  type: string;
  errorCode: number;
  errorMessage: string;
}

/** Timestamped (word-aligned) lyrics payload. */
export interface TimestampedLyrics {
  alignedWords: AlignedWord[];
  waveformData: number[];
  hootCer: number;
  isStreamed: boolean;
}

/** WAV conversion record-info payload. */
export interface WavConversionRecord {
  taskId: string;
  musicId: string;
  musicIndex: number;
  callbackUrl: string;
  completeTime: string;
  response: { audioWavUrl: string };
  successFlag: string;
  createTime: string;
  errorCode: number;
  errorMessage: string;
}

/** Vocal / stem separation record-info payload. */
export interface VocalSeparationRecord {
  taskId: string;
  musicId: string;
  musicIndex: number;
  callbackUrl: string;
  completeTime: string;
  response: {
    id: string;
    originUrl: string;
    originData: OriginData[];
    instrumentalUrl: string;
    vocalUrl: string;
    backingVocalsUrl: string;
    drumsUrl: string;
    bassUrl: string;
    guitarUrl: string;
    keyboardUrl: string;
    percussionUrl: string;
    stringsUrl: string;
    synthUrl: string;
    fxUrl: string;
    brassUrl: string;
    woodwindsUrl: string;
  };
  successFlag: string;
  createTime: string;
  errorCode: number;
  errorMessage: string;
}

/** MIDI generation record-info payload. */
export interface MidiGenerationRecord {
  taskId: string;
  recordTaskId: number;
  audioId: string;
  callbackUrl: string;
  completeTime: number;
  midiData: {
    state: string;
    instruments: MidiInstrument[];
  };
  successFlag: number;
  createTime: number;
  errorCode: string;
  errorMessage: string;
}

/** Music-video (MP4) record-info payload. */
export interface MusicVideoRecord {
  taskId: string;
  musicId: string;
  musicIndex: number;
  callbackUrl: string;
  completeTime: string;
  response: { videoUrl: string };
  successFlag: string;
  createTime: string;
  errorCode: number;
  errorMessage: string;
}

/** Cover generation record-info payload. */
export interface CoverGenerationRecord {
  taskId: string;
  parentTaskId: string;
  callbackUrl: string;
  completeTime: string;
  response: { images: string[] };
  successFlag: number;
  createTime: string;
  errorCode: number;
  errorMessage: string;
}

/** Credits remaining. */
export type CreditsResponse = number;

/** Voice validation info payload. */
export interface VoiceValidateInfo {
  taskId: string;
  validateInfo: string;
  status: VoiceStatus;
  errorCode: number;
  errorMessage: string;
}

/** Voice generation record-info payload. */
export interface VoiceRecordInfo {
  taskId: string;
  voiceId: string;
  status: VoiceStatus;
  errorCode: number;
  errorMessage: string;
}

/** Voice availability check payload. */
export interface CheckVoiceResponse {
  isAvailable: boolean;
}

/** Uploaded file metadata. */
export interface UploadFileResponse {
  fileName: string;
  filePath: string;
  downloadUrl: string;
  fileSize: number;
  mimeType: string;
  uploadedAt: string;
}
